units: "real"
atom_style: "full"
pair_style: "lj/cut/coul/long 10.0"
pair_coeff: "* *"
kspace_style: "ewald 1.0e-4"
bond_style: "harmonic"
angle_style: "harmonic"
dihedral_style: "opls"
fix:
  - "1 all npt temp 300.0 300.0 100.0 iso 1.0 1.0 1000.0"
run: 10000
thermo: 100
thermo_style: "custom step temp press density"
